est_params:
  n_estimators:
    - 50
    - 100
    - 150
  max_depth:
    - 6
    - 8
  eta:
    - 0.05
    - 0.15
    - 0.3
  verbosity:
    - 0

windows:
  - 16
  - 32
  - 64
tresholds:
  - 0.1
  - 0.2
  - 0.3
ngramms:
  - 2
  - 3
  - 4
#path to ecg records 
path: "C:/Users/nikit/Downloads/ecg-master/ecg-master/records"