est_params:
  c:
    - 0.01
    - 0.1
    - 1
    - 2
    - 10

windows:
  - 5
  - 8
  - 12
  - 16
  - 20
tresholds:
  - 0.2
  - 0.3
  - 0.4
  - 0.5
ngramms:
  - 2
  - 3
  - 4
#path to ecg records 
path: "C:/Users/nikit/Downloads/ecg-master/ecg-log-reg/records"