est_params:
  c:
    - 0.01
    - 0.1
    - 0.5
    - 1
    - 10

windows:
  - 16
  - 32
  - 64
tresholds:
  - 0.1
  - 0.2
  - 0.3
ngramms:
  - 2
  - 3
  - 4
#path to ecg records 
path: "C:/Users/nikit/Downloads/ecg-master/ecg-log-reg/records"