est_params:
  n_estimators:
    - 50
    - 100
    - 150
  max_depth:
    - 4
    - 6
    - 8
  eta:
    - 0.05
    - 0.1
    - 0.2
    - 0.3

windows:
  - 16
  - 32
tresholds:
  - 0.2
  - 0.3
  - 0.4
ngramms:
  - 2
  - 3
  - 4
#path to ecg records 
path: "C:/Users/nikit/Downloads/ecg-master/ecg-master/records"